qvalue: 2.30.0
clusterProfiler: 4.6.2
lubridate: 1.9.3
forcats: 1.0.0
purrr: 1.0.1
readr: 2.1.4
tidyr: 1.3.0
tibble: 3.1.8
tidyverse: 2.0.0
pairwiseAdonis: 0.4.1
cluster: 2.1.4
vegan: 2.6-6.1
lattice: 0.20-45
permute: 0.9-7
stringr: 1.5.0
magrittr: 2.0.3
coin: 1.4-3
survival: 3.4-0
plyr: 1.8.9
dplyr: 1.1.0
pbapply: 1.7-2
data.table: 1.14.6
openxlsx: 4.2.5.1
ggpubr: 0.5.0
ggplot2: 3.4.4
yaml: 2.3.7
flowCore: 2.10.0

